[package]
authors = []
edition = "2021"
name = "ortex"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "ortex"
path = "src/lib.rs"

[workspace]
resolver = "2"

[dependencies]
ex_mas_ai = {git = "ssh://git@versioning.unidash.no/maskon-as/client/ex_mas_ai.git", tag = "v0.1.1"}
half = "2.7.1"
ndarray = "0.16.1"
num-traits = "0.2.19"
ort = {version = "2.0.0-rc.10", features = [
  "half",
  "cuda",
  # "directml",
  "tensorrt", 
  # "coreml",
]}
ort-sys = {version = "=2.0.0-rc.10", default-features = false}
rustler = "0.37"
rustls = "0.23.34"
tracing-subscriber = {version = "0.3", features = ["env-filter", "fmt"]}

# [profile.dev]
# debug = true # Enables full DWARF/PDB symbols (default on most platforms)

[profile.dev]
opt-level = 3

[features]
# ONNXRuntime Execution providers
# coreml = ["ort/coreml"]
# directml = ["ort/directml"]
cuda = ["ort/cuda"]
tensorrt = ["ort/tensorrt"]
